### ISSUE TITLE
Make deleting activities optional?

### ISSUE THREAD

**Issue by herbdool** [fuzionnz/nz.co.fuzion.deleteoldbulkmailings#5]
I was hoping that this extension would leave the activity record on the contact so that we'd have some record that the contacts received mailings. Can this be made optional?

**Comment by jitendrapurohit** [comment]
The latest update adds an extra param `skip_activity_delete` to the job. If set, the activities won't be deleted. Added in the doc as well - https://github.com/fuzionnz/nz.co.fuzion.deleteoldbulkmailings#usage

**Comment by herbdool** [comment]
Thank you!
